name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual CI run'

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Node.js setup & cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --legacy-peer-deps

      # Python setup & backend test (pyproject.toml)
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install .
        working-directory: apps/backend
      - run: pytest apps/backend || echo "No backend tests found, skipping."

      # Identify affected projects
      - name: Identify affected projects
        id: affected-projects
        run: |
          AFFECTED_PROJECTS=$(npx nx show projects --affected)
          echo "Affected projects: $AFFECTED_PROJECTS"
          echo "projects=$AFFECTED_PROJECTS" >> $GITHUB_OUTPUT

      # Nx lint/test/build/typecheck for affected projects
      - name: Lint, test, build, and typecheck affected projects
        env:
          AFFECTED_PROJECTS: ${{ steps.affected-projects.outputs.projects }}
        run: |
          echo "Running checks for affected projects: $AFFECTED_PROJECTS"
          npx nx affected -t lint test build typecheck

      # start frontend/backend service and do e2e test
      - run: |
          npx nx serve backend &
          npx nx serve frontend &
          npx wait-on http://localhost:3000 http://localhost:8000
          npx nx run frontend-e2e:e2e || echo "No e2e tests found, skipping."
