name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual CI run'

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Node.js setup & cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Set up base and head refs for nx affected
      - name: Set base and head SHAs
        uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: 'main'

      - name: Identify affected projects
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "NX_BASE: ${{ env.NX_BASE }}"
          echo "NX_HEAD: ${{ env.NX_HEAD }}"
          echo "Affected projects:"
          npx nx show projects --affected --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}
          
      # Python and UV setup for backend projects
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: astral-sh/setup-uv@v3

      # Run all checks for affected projects
      - name: Run CI checks for affected projects
        run: |
          npx nx affected -t lint test build typecheck --base=${{ env.NX_BASE }} --head=${{ env.NX_HEAD }}

